# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: SOOS Core SCA
      # You may pin to the exact commit or the version.
      # uses: soos-io/soos-sca-github-action@aee6c3c3896fba5b555c8b30b8ef31218d360245
      uses: soos-io/soos-sca-github-action@v1.2.4
      with:
        # SOOS Client Id
        client_id: jtrsqusyr
        # SOOS API Key
        api_key: MTlkMDM2ZjQtNzZhYy00M2ZlLWJiZjktNzY2OTAxNDhkYWNm          
